"""empty message

Revision ID: 882f87d88f5a
Revises: 
Create Date: 2023-05-13 21:44:08.025544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '882f87d88f5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newhouseinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('tag',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newhouseinfo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tag',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
